<a href="https://colab.research.google.com/github/gretagh93/NNs_Colab_Notes/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors - Pytorch

In [1]:
import torch
import numpy as np

## Inicialize

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

Diferences between ones_like and rand_like functions

In [3]:
# ones_like: Retorna un tensor omplert amb 1. Tindrà la mateixa mida que # l'input donat.
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [4]:
# rand_like: Retorna un tensor omplert amb nombres aleatoris d'una 
# distribució uniforme en l'interval [0, 1). Tindrà la mateixa mida 
# que l'input donat.
x_ones = torch.rand_like(x_data, dtype=torch.float)
print(x_ones)

tensor([[0.7654, 0.2584],
        [0.5829, 0.3009]])


Using shape, a tuple of tensor dimensions.

In [5]:
shape = (4, 4,)
rand_tensor = torch.rand(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.3978, 0.9317, 0.3785, 0.5217],
        [0.1532, 0.6120, 0.6379, 0.1315],
        [0.9235, 0.3594, 0.2190, 0.8067],
        [0.1763, 0.2802, 0.9461, 0.7064]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 



## Tensor Attributes

In [6]:
tensor = torch.rand(3, 4)

# shape
print(f"Shape: {tensor.shape}")
# datatype
print(f"Datatype: {tensor.dtype}")
# device
print(f"Device: {tensor.device}")

Shape: torch.Size([3, 4])
Datatype: torch.float32
Device: cpu


## Operations

In [7]:
# Change of device
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

In [8]:
# Indexing
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# Add
print(torch.add(tensor, 20))

tensor([[21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.]])


### Multiply Element-Wise vs Matrix Multiplication

In [10]:
# Element-wise product
print(tensor.mul(tensor))
print(tensor * rand_tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[0.3978, 0.0000, 0.3785, 0.5217],
        [0.1532, 0.0000, 0.6379, 0.1315],
        [0.9235, 0.0000, 0.2190, 0.8067],
        [0.1763, 0.0000, 0.9461, 0.7064]])


In [11]:
# Element-wise product
a = torch.randn(3)
torch.mul(a, 100)
b = torch.randn(4, 1)
c = torch.randn(1, 4)
torch.mul(b, c)

tensor([[-0.8626,  0.7906,  0.7611,  0.3295],
        [-0.1885,  0.1727,  0.1663,  0.0720],
        [ 0.9590, -0.8790, -0.8462, -0.3663],
        [-0.6082,  0.5575,  0.5366,  0.2323]])

In [12]:
# Matrix Multiplication
# mT -> Transpose matrix
print(tensor.matmul(tensor.mT))
print(tensor @ tensor.mT)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


## Bridge with Numpy

In [13]:
t = torch.ones(5)
print(f"Pycharm Tensor: {t}")
n = t.numpy()
print(f"Numpy Array: {n} \n")

# Differences between add_ and add
# t = torch.add(t, 20)
t.add_(1)
t = torch.add(t, 20)


print(f"Pycharm Tensor: {t}")
print(f"Numpy Array: {n}")

Pycharm Tensor: tensor([1., 1., 1., 1., 1.])
Numpy Array: [1. 1. 1. 1. 1.] 

Pycharm Tensor: tensor([22., 22., 22., 22., 22.])
Numpy Array: [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [14]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
